#!/usr/bin/env bash

if
  [[ -s "/home/ubuntu/.rvm/gems/ruby-2.7.0/environment" ]]
then
  source "/home/ubuntu/.rvm/gems/ruby-2.7.0/environment"
  exec executable-hooks-uninstaller "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ubuntu/.rvm/gems/ruby-2.7.0/environment'" >&2
  exit 1
fi
